function model = getMiniCheetahVisionModel(fb_joint_type)
% This function builds the floating base model of the Mini Cheetah
% quadruped using the conventions of the spatialv2 library

%% Robot Parameters
%bodyMass = 4.0;
bodyMass = 5.0; % testing for jump optimization
bodyLength = 0.20275 * 2;
bodyWidth = 0.049 * 2;
bodyHeight = 0.05 * 2;

abadLinkLength = 0.068;
hipLinkLength = 0.2085;
kneeLinkLength = 0.2;
% kneeLinkY_offset = 0.004;

abadRotInertia = 1e-6 .* [381, 58, 0.45;...
    58, 560, 0.95;...
    0.45, 0.95, 444];
abadCOM = [0, 0.036, 0];
abadInertia = spatialInertia(0.54, abadCOM, abadRotInertia);

hipRotInertia = 1e-6 .* [1983, 245, 13;...
    245, 2103, 1.5;...
    13, 1.5, 408];
hipCOM = [0, 0.016, -0.02];
hipInertia = spatialInertia(0.634, hipCOM, hipRotInertia);

kneeRotInertia = 1e-6 .* [6, 0, 0;...
    0, 248, 0;...
    0, 0, 245];
kneeCOM = [0, 0, -0.061];
kneeInertia = spatialInertia(0.064, kneeCOM, kneeRotInertia);

bodyRotInertia = 1e-6 .* [11253, 0, 0;...
    0, 56203, 0;...
    0, 0, 42673]; % original
bodyCOM = [0, 0, 0];
bodyInertia = spatialInertia(bodyMass, bodyCOM, bodyRotInertia);

abadLocation = [bodyLength, bodyWidth, 0] * 0.5;
hipLocation = [0, abadLinkLength, 0];
kneeLocation = [0, 0, -hipLinkLength];
footLocation = [0, 0, -kneeLinkLength];

robot = struct(...
    'bodyMass',bodyMass,...
    'bodyLength', bodyLength,...
    'bodyWidth', bodyWidth,...
    'bodyHeight',bodyHeight,...
    'bodyInertia',bodyInertia,...
    'abadInertia',abadInertia,...
    'abadLocation',abadLocation,...
    'hipInertia',hipInertia,...
    'hipLocation',hipLocation,...
    'kneeInertia',kneeInertia,...
    'kneeLocation',kneeLocation,...
    'footLocation',footLocation,...
    'leg_rad',.02,...
    'abadGearRatio',6.0,...
    'hipGearRatio',6.0,...
    'kneeGearRatio',9.33,...
    'motorKT',0.05,...
    'motorR',0.173,...
    'motorTauMax',3.0,...
    'motorVelMax',240.0,...
    'batteryV',24);

%% Build the Model
switch fb_joint_type
    case 'eul'
        model = buildQuadrupedModel(robot);
    case 'quat'
        model = buildQuadrupedModel_Quat(robot);
    case 'SE3'
        error('SE3 floating base model not ready yet')
    otherwise
        error('Invalid floating base joint type given')
end
model.name    = 'MiniCheetahVision';
model.fb_type = fb_joint_type;
model.params  = robot; 


